### ISSUE TITLE
Configure Google Analytics for ekumenlabs.com

### ISSUE THREAD

**Issue by adamantivm** [creativa77/creativa77.github.io#19]
And test it before launching

**Comment by sanbor** [comment]
It's working!

![image](https://cloud.githubusercontent.com/assets/51512/6349735/48011dfe-bc0c-11e4-92a1-1e1a34bb1743.png)


@adamantivm I just added you as admin of the google analytics account.

**Comment by adamantivm** [comment]
thank you very much @sanbor! Can you please change and add my creativa77.com.ar account instead? I will close the issue once I can confirm access to the account

**Comment by sanbor** [comment]
Oh, sorry about that. I just added you again with the `creativa77.com.ar` email account.

**Comment by adamantivm** [comment]
:+1:  confirmed
