### ISSUE TITLE
Update footer to make it less explicit we are in Argentina

### ISSUE THREAD

**Issue by adamantivm** [creativa77/creativa77.github.io#21]

**Comment by sanbor** [comment]
We could just remove the address from the footer and just leave the copyright notice, the phone and email.

**Comment by adamantivm** [comment]
Yes. For phone number, use: +1(408)540-6197

**Comment by sanbor** [comment]
The new footer has been deployed.

![image](https://cloud.githubusercontent.com/assets/51512/6352497/e7582090-bc21-11e4-9de1-5cd951207889.png)
