### ISSUE TITLE
Home page: define which four areas of work to use

### ISSUE THREAD

**Issue by adamantivm** [creativa77/creativa77.github.io#22]

**Comment by adamantivm** [comment]
NOTE: That I do not like the wording I am using. I am focusing on choosing the topics, not on finding an appealing way to convey them yet.

I would go with the following four areas for now:

 - **Mobile Applications**: Applications and core technology for smartphones, wearable and embedded devices, with a special focus on Android 
 - **Web Applications**: Applications and core technology for modern browsers
 - **Robotics Software**: Active participants of the ROS community, with special focus on ROS on Android and RobotWebTools and solid experience in planning, ground and air vehicle navigation, motion controllers
 - **Usable interfaces**: Easy-to-use interfaces to allow non-technical users to intuitively adopt and effectively use all sorts of technology-based products

NOTE: I can imagine a diagram with Mobile and Web at the bottom as basic skills, Robotics building on top of that (that's why we focus on Mobile robotics and Web robotics) and then Usable Interfaces on top of all of it, meaning that we can integrate Robotics, Mobile and Web technology into usable user-centered systems.

Others that we can swap-in later, only for the record:
 - **Remote Work / Collaboration**: Tools and practices to increase efficiency of your company by incorporating geographically distributed team members in an effective way 
 - **Live Streaming Video**
 - **Cryptography and anti-piracy**

**Comment by adamantivm** [comment]
@manzato please chime in if you differ.
@creativa77/florian is this enough input to work on the copy text for this part of the Home Page?

**Comment by adamantivm** [comment]
@florianpestoni (notifying proper user)

**Comment by florianpestoni** [comment]
Check out
https://docs.google.com/document/d/10XLZS5mNpusxKsib97unGF79ElEN2pi0PeDy8fIlOMk/edit#

Feel free to comment/add content.

**Comment by adamantivm** [comment]
Closing this issue and continuing in #20
